### ISSUE TITLE
Upgrade to Go 1.15+ might break compatibility with some F5 instances

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-f5#37]
## Description

With Go 1.15+, the standard crypto library [will no longer use the CommonName (CN) attribute of a certificate to validate hosts by default](https://golang.org/pkg/crypto/x509/#Certificate.VerifyHostname). This might impact old setups which still have certificates generated this way, as we can seee in some client's enviroments.

## Expected Behavior

We should either hold the go version to <1.15, or provide a workaround for this.

### Possible workarounds

- Add/recommand a `-tls-skip-verify` flag
- Somehow make the agent set `GODEBUG=x509ignoreCN=0` for this particular integration, or add instructions for the user to do this

**Comment by paologallinaharbur** [comment]
`GODEBUG=x509ignoreCN=0`  was deprecated as well in 1.16 and finally removed in 1.17. Therefore it is not a workaround anymore

Extra context https://cloud.redhat.com/blog/details-on-https-common-name-deprecation-in-openshift-4.10
 - [RFC 6125](https://www.rfc-editor.org/rfc/rfc6125#section-6.4.4), published in 2011
```
Therefore, if and only if the presented identifiers do not include a
   DNS-ID, SRV-ID, URI-ID, or any application-specific identifier types
   supported by the client, then the client MAY as a last resort check
   for a string whose form matches that of a fully qualified DNS domain
   name in a Common Name field of the subject field (i.e., a CN-ID)
```

**Comment by paologallinaharbur** [comment]
Personally, I would do the change now. As a workaround IF REQUESTED we can add the classical skipVerify in [args](https://github.com/newrelic/nri-f5/blob/ddd0d0718b75eee62204cb5582ec01d20f2308e2/src/arguments/arguments.go#L12) and possibly leverage as well https://github.com/newrelic/infra-integrations-sdk/blob/877315449a79bf6e41ba190628a1f0960c4edbae/http/client.go#L25

**Comment by paologallinaharbur** [comment]
In the Alvaro’s environment the integration fails 1.18 with the error:
```
[ERR] Encountered fatal error: Post "https://ec2-44-204-155-207.compute-1.amazonaws.com:8443/mgmt/shared/authn/login": x509: certificate relies on legacy Common Name field, use SANs instead
```
On the other hand there are two solutions:
 - with `nrHttp.WithTLSInsecureSkipVerify()` it works, I’ll add a new flag to enable it
 - the user could  update SANs through the webUI and it works also without the `TLSInsecureSkipVerify`, I can document it

**Comment by carlossscastro** [comment]
Waiting for documentation to be merged: https://github.com/newrelic/docs-website/pull/8727

**Comment by kang-makes** [comment]
Docs merged :)
