### ISSUE TITLE
Flaky test fails ramdomly

### ISSUE THREAD

**Issue by kang-makes** [newrelic/nri-f5#49]
## Description
A job that has been run more than one time with the same commit seems to fail randomly during the Unit test phase

https://github.com/newrelic/nri-f5/runs/3927637638?check_suite_focus=true
https://github.com/newrelic/nri-f5/runs/3927692814?check_suite_focus=true

## Expected Behavior
Tests should be consistent.

## Steps to Reproduce
As any race condition there is no reproducible way but test until it fails again.

## Your Environment
It is not in my environment but Github action's one. This should be reproducible (with enough attempts) locally.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
